default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password: password

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
  host: db

production:
  <<: *default
  database: myapp_production
  username: postgres
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
