name: CI/CD with Fly Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        options: |
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          -e POSTGRES_USER=postgres
          -e POSTGRES_PASSWORD=password
    steps:
      - uses: actions/checkout@v3

      - name: Wait for DB to be ready
        run: sleep 10  # データベースの起動待機

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up Database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        run: |
          bundle exec rspec

  deploy:
    name: Deploy app
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --ha=false
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
