name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: verify
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    container:
      image: ruby:3.3.4
      env:
        RAILS_ENV: test
        POSTGRES_HOST: postgres
        RAILS_DATABASE_USER: postgres
        RAILS_DATABASE_PASSWORD: password
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install wait-for-it
        run: curl -o /usr/local/bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x /usr/local/bin/wait-for-it.sh

      - name: Wait for Postgres
        run: /usr/local/bin/wait-for-it.sh postgres:5432 --timeout=60 --strict -- echo "Postgres is up"

      - name: bundler set up
        run: |
          gem install bundler
          bundle install
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: db setup
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Precompile assets
        run: |
          bundle exec rake assets:precompile
      - name: Install Yarn
        run: |
          npm install --global yarn
      - name: verify
        run: |
          bundle exec rspec

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}